sudo: false
language: ruby
rvm:
- 2.2.7
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  gem: spree_mollie_gateway
  on:
    tags: true
    repo: mollie/spree-mollie-gateway
  api_key:
    secure: jHnI6k4LZnjjHj21h0Lwf3OTW7n1l9sTHq7uxCpCio5Iz9Ag83q29YpYwuPXfkuPeK34gbnys8WSDqaGRbrqxJHQBwNyqBlhH6VEePCUrVpgx3wDn4sTuqbOXWEIT9RZVNh/ZOjs3LoKgF3HRwd+5/uJd0sWknoCeNpdYUv8idcYV243QxaH8taWb7axQVsFgJkJ4zmzC91LfXiDhsY29Q5u4I72iEOynL4Cnmy7ilXk0wjxkVPJ1vdN0IZo0+4BmjYlutZLA58m+GOXGOItAVk0DsziXXlu1Sv8h3GcK8PZMviRNCfi383V4KbSLiTOOg8sIT8lI5tHPVAlbW5kwrePwZONx27t3TaHfla+e6NK0bbBRFTyWcwa8VhBm/Qi6MKdR3Jh8t/EOFIHvkscZgZ+i8qe5wxldAmakaOOM54vvQwyNMF2Zze+ohk1gGBYycAiOeuknh35Q7jBsuNAQkNNXzMBgUJLnNZcVIN9sNk9k8Q4oXn1qfez+VKT1/wqIXeU2Ll4wcWvMoR1f9xu0+dAf1mFPocSbFd3AE5fHF0F3RSLL286rABCB8Ig3g6rWUmEmA95W0fKCBayjmJ2XE2fhmeYcJhZvWrVz6uwsRSld4FgpQ+lCy/9BLgWEhKgnGS2yvHKS8V2SrUR+KnCMT9WSZl8bw1OCYYo1/9TpOY=
env:
  matrix:
    secure: ox+mZeCceryjTfSOkkShvhH/VaAtTIo9inCO/jqUlzxFWpcNfr0ZsC9cV1/cFabiav16mktPw5GWDGgAHg5zY2+V1EXEz3mnYSoBbDE1GtjkMD32/oxfDdprNiBIkW98OU7pqqS6M+cUsxMKDFRydaExSCZE3eJ471T/6ig4KRcis725Lxra8PQ+y40WSEVORifpL592UgR7JmM0rthgfowBfkmqDnDgJ6mpMb5LBSq71URZuopQIe59wjH1DYG8Ppb7d3Vf+3nmnnVtR2e5U9kcn4LeNCK2IuxawnEgxcBnyKTV1zoLIEnztkUbioMlkZwMURNCE9p2JCWRAOc2R4zDLZwfphTrSsE8hmtEU3APSmqr5Z7aGb7xxZ3K9tVsvPGO7YAwJpLdckE18ol+tr9UZc8GDyPAwGiIdF2o02SdlVwIlP5BpPolTsIycQiA5DlLETMPv9g1qxgEdvzCgnZEyaN/gssulvsO+wtP7fRufJaNJuCvoXi5MMcCe9aK/AVq50wDNiQEOvyfXAUOrkLgVzWM0qiaa+gDIX6gzf5mz/BSqfaAsMFZafKpbbInMrRhr3v32z09qCfADBv3C8udCqeyYlqUhX1DtfUt74eNiYD6WzoYHssAF3zEq9NK49NFeBpJbaxmPa8vJo+z0HWiFYXj1ydUMfwX8A+shRM=
