sudo: false
language: ruby
rvm:
- 2.2.7
before_install: gem install bundler -v 1.16.1
deploy:
  provider: rubygems
  gem: spree_mollie_gateway
  on:
    tags: true
    repo: mollie/spree-mollie-gateway
  api_key:
    secure: jHnI6k4LZnjjHj21h0Lwf3OTW7n1l9sTHq7uxCpCio5Iz9Ag83q29YpYwuPXfkuPeK34gbnys8WSDqaGRbrqxJHQBwNyqBlhH6VEePCUrVpgx3wDn4sTuqbOXWEIT9RZVNh/ZOjs3LoKgF3HRwd+5/uJd0sWknoCeNpdYUv8idcYV243QxaH8taWb7axQVsFgJkJ4zmzC91LfXiDhsY29Q5u4I72iEOynL4Cnmy7ilXk0wjxkVPJ1vdN0IZo0+4BmjYlutZLA58m+GOXGOItAVk0DsziXXlu1Sv8h3GcK8PZMviRNCfi383V4KbSLiTOOg8sIT8lI5tHPVAlbW5kwrePwZONx27t3TaHfla+e6NK0bbBRFTyWcwa8VhBm/Qi6MKdR3Jh8t/EOFIHvkscZgZ+i8qe5wxldAmakaOOM54vvQwyNMF2Zze+ohk1gGBYycAiOeuknh35Q7jBsuNAQkNNXzMBgUJLnNZcVIN9sNk9k8Q4oXn1qfez+VKT1/wqIXeU2Ll4wcWvMoR1f9xu0+dAf1mFPocSbFd3AE5fHF0F3RSLL286rABCB8Ig3g6rWUmEmA95W0fKCBayjmJ2XE2fhmeYcJhZvWrVz6uwsRSld4FgpQ+lCy/9BLgWEhKgnGS2yvHKS8V2SrUR+KnCMT9WSZl8bw1OCYYo1/9TpOY=
env:
  matrix:
    secure: ivP6D01JO/XM60moW91K+PqHz1rK0Ed8mA6RIoMp7xqSNEDOQxe5ms6RF1aVB978dT4BB1bGxR0EDyJgpUAuyJ6rf1xhszDwxtmj1VbMj/ljjrrw0M8DSfXVkMmvmohDam1JryXy4b/PDx0DdQSPzviLdfFnr3MYvPxLHe2XNzcJeBK+RZZduvRTKfPcwopJqpQqUEXl+aj80MoL9zTds+FZ2K20YFY4jskeD4xrKJAxKCxEyepEewhSvqtQj2jcuEGhn1Mnyb00saCFIsWfE3jbEL3ezYxkuuHNAqT5SkWpKaU1nVFHI8pFm+upMlanE9Dt7a8jTwn+iFxSpgLFzvzQPX23hlEa1v+RxmGvs0b55oiNgXBveYEEbrjcdmbQXQGJ0FWtwlQpTEls+rT5vx3SkzPO1v6dZtpEFHymyPyBUHZnzJcMXwSl8eHzj8CskFE24fri6+PZvmZUXQ3YnGEMB5MxjaTeM3exwdbqqvtACKIV/b1nGwH+2ogZqnECz40c0vzqMYjAQvGXVCpwBNK1TSPEK7l9UgVGH0DVz8fJEx7qpPj7nWMfINSASuBlpXXAjy9HPDqZsum5RejwovVTwoT7+n+wT+AS48lHaVcWFfFGGwpSm7tx9OHYT7sKcDoaPpTEKd5mKaYl9fKAzZujKZ5CKm3EBHaQmZQ5Upk=
